services:
  postgres:
    image: postgres:17
    container_name: poa_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: poa
      POSTGRES_PASSWORD: poatest123
      POSTGRES_DB: poa
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  api:
    image: poa-api
    container_name: poa-api
    build:
      context: ./POALaboratoriniai
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=poa;Username=poa;Password=poatest123"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - postgres

volumes:
  pgdata: